pluginManagement {
    repositories {
        maven { url "https://maven.minecraftforge.net/" }
        maven { url "https://maven.fabricmc.net/" }
        gradlePluginPortal()
    }
}

// Reference the parent project for the :common module
includeBuild("..") {
    dependencySubstitution {
        substitute module("net.wolren.land:common") using project(":common")
    }
}

rootProject.name = "pride_land_forge"
